### ISSUE TITLE
Dynamic Captions with DataSource

### ISSUE THREAD

**Issue by tenkotwo118** [dimsemenov/photoswipe-dynamic-caption-plugin#14]
Hey, not sure if this is an issue, but I've been trying to get DataSource from the page https://photoswipe.com/data-sources/ working with the Dynamic Caption plugin  for a few days, but nothing I try has worked. Is it possible?

My goal is to have one image open up when clicked revealing an album or gallery of other images with their own captions or at least one general caption for all of them. This works using the code from the DataSource page and using an image instead of button and adding the id of the button to the image, but no captions.

Has anyone tried this before? Any hints would be greatly appreciated! Thanks.

**Comment by dimsemenov** [comment]
Use `captionContent` option, it should return the caption HTML text, you may parse the data however you wish in it. This may help - https://github.com/dimsemenov/photoswipe-dynamic-caption-plugin/issues/10

**Comment by tenkotwo118** [comment]
Thank you so much!
