### ISSUE TITLE
Possibility to get a tagged release?

### ISSUE THREAD

**Issue by joshsedl** [dimsemenov/photoswipe-dynamic-caption-plugin#21]
There are currently multiple releases for this plugin on [npm](https://www.npmjs.com/package/photoswipe-dynamic-caption-plugin), but none on GitHub, this would really help the [photoswipe 5.x](https://www.drupal.org/project/photoswipe) release of the Drupal module, since not all users can download this plugin through composer's "npm-asset" or know how to clone this repo. And since cdn is not an option in some countries, due to data protection regulations and npm not part of the Drupal eco system a release would be needed.

Thank you! 🙂

**Comment by JPustkuchen** [comment]
Please note: At NPM & Asset Packagist, there are releases, but they are not mirrored to GitHub: https://www.npmjs.com/package/photoswipe-dynamic-caption-plugin

**Comment by joshsedl** [comment]
Thanks, @dimsemenov! :)
