### ISSUE TITLE
Option to remove zoom animation from captions

### ISSUE THREAD

**Issue by artneo-io** [dimsemenov/photoswipe-dynamic-caption-plugin#23]
Hello! Let me start by saying thanks for the awesome lib! 🏆

Is there a way to disable the zoom animation only for captions?
`showHideAnimationType: 'zoom'`

![remove-zoom-caption-animation](https://github.com/dimsemenov/photoswipe-dynamic-caption-plugin/assets/17693529/fd19ecd8-43cf-4eff-b1b1-949b1635d88e)

**Comment by dimsemenov** [comment]
This can happen if you have `data-cropped="true"` due to how it works. There is no option to disable it for now unless you hide the caption initially and display it only after the gallery is fully opened.

**Comment by artneo-io** [comment]
![reduced-caption-animation](https://github.com/dimsemenov/photoswipe-dynamic-caption-plugin/assets/17693529/48b5e3fa-d7d3-4f35-b0cd-2e0d596a16bb)

I found out a good solution, you just need to add the following custom CSS to `photoswipe-dynamic-caption-plugin.css`

```
.pswp__dynamic-caption {
  color: #fff;
  position: absolute;
  width: 100%;
  left: 0;
  top: 0;
  /* transition: opacity 120ms linear !important; */
  /* comment out this declaration */
}
.pswp__item div.pswp__dynamic-caption {
  opacity: 0;
  transition: opacity 125ms;
  transition-delay: 350ms;
}
.pswp--ui-visible .pswp__item div.pswp__dynamic-caption {
  opacity: 1;
}
.pswp__item:not(.pswp--ui-visible .pswp__item) div.pswp__dynamic-caption {
  opacity: 0;
  transition: opacity;
}
```
