### ISSUE TITLE
Amateur question

### ISSUE THREAD

**Issue by gemisch** [dimsemenov/photoswipe-dynamic-caption-plugin#24]
A stupid question from a clueless amateur: Why do the images on my [test page](https://elkemischling.at/test) open in a new window? Many thanks for an answer.

**Comment by dimsemenov** [comment]
You have an error in browser console that explains why

```
Uncaught TypeError: Failed to resolve module specifier "dist/photoswipe-dynamic-caption-plugin.esm.js". Relative references must start with either "/", "./", or "../".
```

Make sure u provide either an absolute path (that starts with `https://`) or a relative one as the error suggests.

**Comment by gemisch** [comment]
Thank you very much for the quick reply.
Best wishes to Ukraine and stay strong.
